# Generated by Django 3.0.8 on 2020-08-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parr', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('longitud', models.CharField(blank=True, max_length=200, null=True)),
                ('latitud', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('imagen', models.ImageField(upload_to='parroquias/')),
                ('historia', models.TextField(blank=True, null=True)),
                ('info_general', models.TextField(blank=True, null=True)),
                ('situacion_geografica', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
                'ordering': ['nombre_parr'],
            },
        ),
    ]
